# Generated by Django 4.2.1 on 2023-08-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_details', models.TextField()),
                ('project_images', models.ImageField(upload_to='projects_images/')),
                ('project_links', models.CharField(max_length=500)),
                ('project_submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
