# Generated by Django 4.2.1 on 2023-08-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bannerimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannerImages',
        ),
    ]
